version: '3.9'

services:
  backend:
    image: node:16.14
    container_name: online_menu
    build: .
    ports:
      - "3001:3001"
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - MONGO_DB_URL=mongodb://db:27017
      - JWT_SECRET=jwt_secret
    depends_on:
      - db
  db:
    image: mongo:5.0.7
    container_name: online_menu_db
    ports:
      - "3002:27017"
    environment:
      - MONGO_DB_URL=mongodb://db:27017
